Revert to last sane version

diff --git a/.github/workflows/prune.yaml b/.github/workflows/prune.yaml
--- a/.github/workflows/prune.yaml
+++ b/.github/workflows/prune.yaml
@@ -1,17 +1,49 @@
-name: "Prune Old Releases"
+name: "Prune Versions"
 
 on:
   workflow_dispatch:
 
 jobs:
-  housekeeping:
+  Prune:
     runs-on: ubuntu-latest
-    name: "prune old releases"
+    name: "Pruning"
     steps:
-      - name: Checkout
-        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
+      - name: Checkout branch
+        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
         with:
           fetch-depth: 0
-      - uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5
-        with:
-          min-versions-to-keep: 200
+          token: ${{ secrets.BOT_TOKEN }}
+
+      - name: Prune App Versions
+        run: |
+          for train in stable incubator dependency core dev games enterprise
+          do
+            for chart in ${train}/*; do
+              if [ -f "${chart}/item.yaml" ]; then
+                maxchartversion=$(ls ${chart} | grep -v item.yaml | sort -Vr | head -n1)
+                maxchartversion=${maxchartversion%/}
+                chartname=$(basename ${chart})
+                  for version in ${chart}/*; do
+                    versionname=$(basename ${version})
+                    if [ -f "${version}/Chart.yaml" ]; then
+                      if [[ "${versionname}" != "${maxchartversion}" ]]; then
+                        echo "Removing older version ${versionname} for ${chartname}"
+                        rm -Rf ${version}
+                      else
+                        echo "${versionname} is the latest version, skipping..."
+                      fi
+                    fi
+                  done
+              else
+                echo "Invalid App"
+              fi
+            done
+          done
+
+      - name: Commit and Push Pruned catalog
+        run: |
+          git config user.name "TrueCharts-Bot"
+          git config user.email "bot@truecharts.org"
+          git add --all
+          git commit -sm "Daily Prune" || exit 0
+          git push
